### ISSUE TITLE
Display changelogs for WordPress plugins

### ISSUE THREAD

**Issue by ocean90** [wearerequired/composer-scripts#6]
It would be nice if `composer update` or `composer outdated` would show a link to the changelog of a plugin.

Example: https://packagist.org/packages/pyrech/composer-changelogs

**Comment by swissspidy** [comment]
What would be the ideal link for the changelog? `https://wordpress.org/plugins/<slug>/#developers`?

**Comment by ocean90** [comment]
Yes, until there's a better one…
