### ISSUE TITLE
Don't require adding scripts

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/composer-scripts#7]
Currently, we suggest adding something like this to a project's `composer.json` file when wanting to use this library:

```json
{
    "scripts": {
        "pre-package-install": "Required\\ComposerScripts\\PluginAvailability::checkAvailability",
        "pre-package-update": [
            "Required\\ComposerScripts\\PluginAvailability::checkAvailability",
            "Required\\ComposerScripts\\PluginAvailability::checkMaintenanceStatus"
        ]
    }
}
```

However, it seems like it should be possible without that by using composer's `EventSubscriberInterface`. That's how https://github.com/pyrech/composer-changelogs seems to do it.

**Comment by ocean90** [comment]
+1

Would like to have the scripts only run when `composer-scripts` is installed globally because I don't see the point for running this during deployment.

**Comment by swissspidy** [comment]
TIL: https://getcomposer.org/doc/articles/plugins.md.

This makes things like #2 and #6 a piece of cake.

For adding tests we can have a look at: https://github.com/pyrech/composer-changelogs/blob/e02cdc091b893774222b0885afcfad3c49ba9382/tests/ChangelogsPluginTest.php

**Comment by swissspidy** [comment]
To use the plugin, add this to `~/.composer/composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/wearerequired/composer-scripts"
        }
    ],
    "require": {
        "wearerequired/composer-scripts": "dev-master"
    }
}
```

After that, run `composer install` in a project's folder to see it in action.
